### ISSUE TITLE
Latest firmware 04_06_2022 can't add pump 

### ISSUE THREAD

**Issue by saper-2** [sarunia/Med-Link-v5#1]
Hi,

I build this v5 (my own board, with usb-c :-D) , I flashed 3 firmware in sequence: flash, disconnect st-link/v3, reset stm8, wait 10sec:
1. First ```Med-Link v3 v4 v5 cleer eeprom.s19```,
2. ```Med-Link v4 v5 firsts BT config without PIN.s19```,
3. ```Med-Link v4 v5 ENG firmware full version 04_06_2022.s19``` - the final firmware.

And after struggling to find working BLE Terminal - found one: **BLE Terminal** by **mightyIT** (for android).

I sent commnad ```OK+CONN``` and med-link replay with ```Send command for pump wakeup ```, and start flashing green led rapidly.

It not asking for pump number, just trying to connect.... This is new med-link so I think it supposed to first ask for pump number, right?

I found on screenshots there should be command ```DELETE``` but med-link replay for it  "unknown command" 😑

When I try older firmware from **old ver** folder (868MHz version) it actually behave like it should, command ```DELETE``` works, and ```OK+CONN``` first ask for pump number...

*So for a time to test how med-link works (on desk with spare pump) I'll use older fw.*

**Comment by sarunia** [comment]
Hi, you must first execute the Z command to enter  pump number, your region and the deviation from of carrier frequency. You can get help from users in the discord group: 
https://discord.gg/9mmTuh5QNB
There is also a Polish instruction on how to start, see this file:
https://docs.google.com/document/d/1IEj3RjBW7zmQpc7kFxs_3AkjGJZIeaZpI0UMZP3jTX8/edit?usp=sharing
good luck

**Comment by saper-2** [comment]
Thanks for links. 

Would be nice to have docu updated with what&where 😉
